# Site settings
title: Design is Choice
about: > # this means to ignore newlines until the next key starts
  Where Dan Bernier stashes his generative art projects.
  The line between noise and art is in how we choose.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://designischoice.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
